Move imagejob deletion to imagelist controller
eraser-dev/eraser pull request #205
Opened 2022-05-20 21:32 UTC by pmengelbert

**What this PR does / why we need it**:
- Delete imagejob in imagelist controller, not from the imagejob controller.
- Update Imagelist status field in the imagelist controller, not in the imagejob controller.

This is necessary because:
- The `imagejob` is being repurposed for management of `collector` pods, and not just `eraser` pods.
- The `imagecollector controller` needs to monitor the `imagejob` to determine when it is completed, in order to proceed to the scanning phase.
- With the current behavior of the `imagejob controller`, the `imagejob` will be cleaned up once the `eraser` pods are finished, preventing the `imagecollector controller` from properly monitoring the `imagejob`.
- In general, the scope that allocates a resource should bear responsibility for freeing that resource. Currently, `imagejob`s are created by the `imagelist controller`, so the `imagelist controller` should clean it up.
- This issue will block further progress on the `imagecollector controller`, so it should be prioritized.

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #200 
Based on top of PR #204, that one should be merged first

**Special notes for your reviewer**:
Please enjoy

2022-05-23 19:36 UTC, pmengelbert commented on controllers/imagelist/imagelist_controller.go
> +		return r.handleJobListEvent(ctx, &imageList, &jobList.Items[0])
This needs additional logic. In addition to an ImageJob being moved to the `Completed` state, we will **also** reach this point when both of the following conditions are true:
1. Reconcile was triggered by an `UpdateEvent` to the `ImageList`
2. There is already and `ImageJob` in progress, and it is not yet complete.

This is related to #203 , and the best thing to do in that case is probably to requeue the `Imagelist`'s `UpdateEvent` for some reasonable time in the future, and to keep punting it until there are no `ImageJob`s in the running state.

2022-05-23 20:21 UTC, cpuguy83 requested changes

2022-05-23 20:21 UTC, cpuguy83 commented on controllers/imagelist/imagelist_controller.go
> +			Labels: map[string]string{consts.ImageJobOwnerLabelKey: imageList.Name},
I think OwnerReference does what we need here?

2022-05-23 20:29 UTC, pmengelbert commented on controllers/imagelist/imagelist_controller.go
> +			Labels: map[string]string{consts.ImageJobOwnerLabelKey: imageList.Name},
Is there a way to select for that in the call to `r.List(...)` when we are listing the existing `ImageJob`s? I couldn't figure that out so I went with the labels instead. I am looking at the `sigs.k8s.io/controller-runtime/pkg/client.ListOptions` struct, and I don't see any option to select by `OwnerReference`.

The other option is to `List` all `ImageJob`s and filter them manually in the controller, is that the better way to go?

2022-05-23 20:48 UTC, pmengelbert commented on controllers/imagelist/imagelist_controller.go
> +			Labels: map[string]string{consts.ImageJobOwnerLabelKey: imageList.Name},
Filtering client-side using `UID`s looks like the way to go, and more reliable than just using the owner's `Name`. Will mark resolved once tests pass

2022-05-25 14:14 UTC, ashnamehrotra commented
Can we also move the functionality from lines 287-310 into the imagelist controller? When we use the imagejob to schedule collector pods we won't need a reference to any imagelist

2022-05-25 16:23 UTC, pmengelbert commented
@ashnamehrotra Yes, that's a very good idea. I was running into problems with this yesterday and the conditional logic was getting messy. I'll work on that now

2022-05-25 22:36 UTC, pmengelbert commented
@ashnamehrotra done

2022-05-27 00:04 UTC, sozercan approved these changes
LGTM

2022-05-27 00:20 UTC, cpuguy83 approved these changes
LGTM

2022-05-27 00:20 UTC, merged