docs: document docs search
eraser-dev/eraser pull request #461
Opened 2022-11-03 23:08 UTC by sozercan

Signed-off-by: Sertac Ozercan <sozercan@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

2022-11-04 12:38 UTC, pmengelbert approved these changes
LGTM

2022-11-04 12:57 UTC, pmengelbert requested changes

2022-11-04 12:57 UTC, pmengelbert commented on docs/README.md
> +Gatekeeper docs website uses Algolia DocSearch service. Please see [here](https://docusaurus.io/docs/search) for more information.
Should be Eraser, no?

2022-11-04 17:10 UTC, sozercan commented on docs/README.md
> +Gatekeeper docs website uses Algolia DocSearch service. Please see [here](https://docusaurus.io/docs/search) for more information.
good catch!

2022-12-06 15:05 UTC, pmengelbert approved these changes
LGTM

2022-12-06 15:20 UTC, merged